# Generated by Django 4.2.4 on 2023-08-07 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser", name="age", field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="full_name",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="gender",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
