# Generated by Django 4.2.4 on 2023-08-07 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_alter_customuser_age_alter_customuser_full_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="customuser", name="age",),
        migrations.RemoveField(model_name="customuser", name="full_name",),
        migrations.RemoveField(model_name="customuser", name="gender",),
    ]
