# Generated by Django 4.2.4 on 2023-08-07 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_customuser_age_customuser_full_name_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(name="customuser", options={},),
        migrations.AlterModelManagers(name="customuser", managers=[],),
        migrations.RemoveField(model_name="customuser", name="age",),
        migrations.RemoveField(model_name="customuser", name="date_joined",),
        migrations.RemoveField(model_name="customuser", name="full_name",),
        migrations.RemoveField(model_name="customuser", name="gender",),
        migrations.RemoveField(model_name="customuser", name="username",),
        migrations.AlterField(
            model_name="customuser",
            name="first_name",
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="is_staff",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="last_name",
            field=models.CharField(max_length=30),
        ),
    ]
